modLoader="javafml"
loaderVersion="[38,)"
license="GNU GPL 3.0"
issueTrackerURL="https://github.com/RecraftorsMC/unruled_api/issues"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="Unruled Api"
displayURL="https://github.com/RecraftorsMC/unruled_api"
logoFile="icon.png"
authors="Recraftors Team, Nerjal Nosk"
description="Expands on the vanilla gamerules to add new gamerules types for other mods to use"
[[dependencies.${mod_id}]]
   modId="forge"
   mandatory=true
   versionRange="[38,)"
   ordering="NONE"
   side="SERVER" # the client could very well be vanilla for all we care
[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18,)"
   ordering="NONE"
   side="BOTH"
